plugins:
  - jekyll-octicons
  - jemoji
  - jekyll-paginate

paginate: 30
paginate_path: "/blog/page:num/"

# permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

