layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-paginate

paginate: 20
paginate_path: "/blog/page:num/"

# permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    description: Game Development, Computer Graphics
    web_url: https://en.wikipedia.org/wiki/C%2B%2B
    image_url: https://github.com/isocpp/logos/raw/master/cpp_logo.png

  - name: Ruby
    description: Ruby on Rails
    web_url: https://en.wikipedia.org/wiki/Ruby_(programming_language)
    image_url: https://www.ruby-lang.org/images/header-ruby-logo.png

  - name: Javscript
    description: Node.js, Express.js
    web_url: https://en.wikipedia.org/wiki/JavaScript
    image_url: https://github.com/voodootikigod/logo.js/raw/1544bdeed6d618a6cfe4f0650d04ab8d9cfa76d9/js.png

  - name: Mathematics
    description: Real Analysis, Discrete Mathematics, Probability
    web_url: https://en.wikipedia.org/wiki/Mathematics
    image_url: https://upload.wikimedia.org/wikipedia/commons/e/eb/Euler%27s_formula.png

  - name: Video Game
    description: DOTA2, Souls Series
    web_url: https://en.wikipedia.org/wiki/Video_game
    image_url: https://upload.wikimedia.org/wikipedia/en/b/bb/Dark_souls_3_cover_art.jpg

  - name: 中国文学
    description: 诗词歌赋,散文
    web_url: https://zh.wikipedia.org/zh-cn/%E4%B8%AD%E5%9B%BD%E6%96%87%E5%AD%A6
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Liji2_no_bg.png/800px-Liji2_no_bg.png

